### ISSUE TITLE
Dúvida sobre rota do app

### ISSUE THREAD

**Issue by KyleKun** [mateusfsilva/coffee-shop#2]
Boa noite!

Gostaria de saber se o ícone no meio da appBar (+) leva para a tela de adicionar algum produto no carrinho, ou se essa tela é chamada ao clicar em qualquer produto na home. Ou se for o caso, ambas as situações são responsáveis por chamar a tela de adicionar o produto no carrinho.

Obrigado!

**Comment by mateusfsilva** [comment]
Bom dia,

Eu pensei em adicionar o item ao carrinho ao seleciona-lo na home. Eu não entendi o que o design queria ao colocar o + na TabBar já que não tem uma tela mostrando como adicionar o item ao clicar no +. Neste caso vale a interpretação de cada um, não tendo uma maneira correta de fazer.

Abs

**Comment by KyleKun** [comment]
Ok, obrigado pelo esclarecimento!

Abs
